modLoader = "javafml"
loaderVersion = "[2,)"
license = "lgpl-3.0"

[[mods]]
modId = "shutdownondeath"
version = "${version}"
displayName = "Shutdown On Death"
authors = "thePlaceholder"
description = '''
A mod that shuts down your computer when you die in Minecraft.
'''

[[dependencies.shutdownondeath]]
modId = "neoforge"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shutdownondeath]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "shutdownondeath.mixins.json"
